"""Reject AI-attribution trailers before they enter history.

Removing one after the fact means a force-push and moved tags across every release from
v0.1 onward -- expensive and avoidable at the source. See D8 in DECISIONS.md.
"""

import re
import sys

BLOCKED = re.compile(
    r"co-authored-by:.*(claude|anthropic|copilot|chatgpt|gpt-4|cursor|codeium|windsurf|devin)"
    r"|generated with|generated by claude|written by claude",
    re.IGNORECASE,
)


def main() -> int:
    msg_path = sys.argv[1]
    with open(msg_path, encoding="utf-8") as f:
        message = f.read()

    match = BLOCKED.search(message)
    if match:
        print(f"BLOCKED: commit message contains an AI-attribution trailer: {match.group(0)!r}")
        print("Remove it and commit again. See D8 in DECISIONS.md.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
